name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Atualizado para a versão mais recente
      - name: Set up Node.js
        uses: actions/setup-node@v3 # Atualizado para a versão mais recente
        with:
          node-version: '20' # Atualizado para usar Node.js 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node server.js